spring:
  application:
    name: hung-oauth
  datasource:
    url: jdbc:h2:file:C:/h2/databaseoauth2
    driverClassName: org.h2.Driver
    username: hung
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2

basic:
  auth:
    client:
      id: hung
      pass: hung
server:  port: 10011
